travis-ci: Adjust timelimit closer to real limit

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,16 +26,16 @@ script:
   - if [ $TRAVIS_OS_NAME == 'linux' ]; then
     export;
     ccache -s;
-    T_START=$(cat INSTALL_BEGIN_TS); T_NOW=$(date +%s); T_AVAIL=$((10 - 3));
+    T_START=$(cat INSTALL_BEGIN_TS); T_NOW=$(date +%s); T_AVAIL=$((48 - 3));
     T_SPINUP=$(($T_NOW - $T_START)); T_LIMIT=$(($T_AVAIL * 60)); T_REMAINING=$(($T_LIMIT - $T_SPINUP));
     echo "Spinup $T_SPINUP, Estimated remaining $T_REMAINING s - $(($T_REMAINING / 60)) m, $T_START, $T_$T_SPINUP" 1>&2;
     date;
     if [ $CC == 'clang' ]; then
     timeout $T_REMAINING make -j2 IGNORE_GIT=1 OVERRIDE_CXX="clang++-3.6" OVERRIDE_CC="clang-3.6" && time ./$MAME -validate ||
-    { export ERROR=$?; if [ $ERROR == 124 ]; then echo "Build exceeded estimated timelimit" 1>&2; fi; echo exiting with code $ERROR; (exit $ERROR); } ;
+    { export ERROR=$?; if [ $ERROR == 124 ]; then echo "Build exceeded estimated timelimit" 1>&2; fi; (exit $ERROR); } ;
     else
     timeout $T_REMAINING make -j4 IGNORE_GIT=1 OVERRIDE_CC="gcc-5" OVERRIDE_CXX="g++-5" TOOLS=1 && time ./$MAME -validate ||
-    { export ERROR=$?; if [ $ERROR == 124 ]; then echo "Build exceeded estimated timelimit" 1>&2; fi; echo exiting with code $ERROR; (exit $ERROR); } ;
+    { export ERROR=$?; if [ $ERROR == 124 ]; then echo "Build exceeded estimated timelimit" 1>&2; fi; (exit $ERROR); } ;
     fi
     elif [ $TRAVIS_OS_NAME == 'osx' ]; then
     unset LDOPTS && make -j2 OPTIMIZE=0 USE_LIBSDL=1 && ./$MAME -validate;
